"""Run the MBIST over JTAG on a design ``wrap-test-access`` wrapped: an IEEE 1687
PDL procedure, its retargeting to TCK-level vectors, and a self-checking
testbench that plays those vectors.

The procedure (:data:`RUN_MBIST`) is written once, as plain data. The PDL text
is rendered from it -- the deliverable a test flow retargets through the ICL
for a tester -- and the same steps drive warptap's own PDL interpreter over the
inserted IJTAG network to produce the vectors, so the two can't disagree. Each
vector is one TCK cycle (TMS, TDI, the expected TDO and whether it's checked)
or a run of the functional clock (the PDL's ``iRunLoop -sck``). The testbench
checks the MBIST's result only through TDO, as a tester would.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .generator import _render_template
from .testbench import _IDLE_HIGH, TB_DIRNAME, TestbenchError, _chmod_x, render_run_script

# The clock the MBIST runs on, as the PDL's iRunLoop -sck names it.
SYSTEM_CLOCK = "clk"
_JTAG_INPUTS = ("tck", "tms", "tdi", "trst_n")
_DRIVEN = ("clk", "rst_n", *_JTAG_INPUTS)
# Control ports wrapping makes JTAG-only: their pins are held at 0, unused.
_JTAG_ONLY_CONTROL = ("test_mode", "bist_start")


@dataclass(frozen=True)
class PdlStep:
    """One PDL command. ``kind`` is "write", "read", "apply" or "runloop".
    A write/read names an instrument (a wrapped port) and a value; a runloop
    runs ``count`` functional-clock cycles."""

    kind: str
    instrument: str | None = None
    value: int | None = None
    count: int | None = None


def run_mbist_steps(run_cycles: int) -> list[PdlStep]:
    """The ``run_mbist`` procedure: enter test mode, start the BIST and hold
    the start (the controller keeps its result only while start stays high),
    run the functional clock for ``run_cycles``, read bist_done=1 and
    bist_fail=0 back, then return the controller to idle."""
    apply = PdlStep("apply")
    return [
        PdlStep("write", "test_mode", 1), apply,
        PdlStep("write", "bist_start", 1), apply,
        PdlStep("runloop", count=run_cycles),
        PdlStep("read", "bist_done", 1), apply,
        PdlStep("read", "bist_fail", 0), apply,
        PdlStep("write", "bist_start", 0), apply,
        PdlStep("write", "test_mode", 0), apply,
    ]


def _binary(value: int, width: int) -> str:
    return "0b" + format(value, f"0{width}b")


def render_pdl(
    top: str,
    steps: list[PdlStep],
    *,
    widths: dict[str, int],
    register_path: dict[str, str],
    icl_file: str | None,
    ir_width: int,
    extest: int,
    bist_cycles: int | None,
    bsdl_file: str | None = None,
) -> str:
    """The ``run_mbist`` procedure as IEEE 1687 PDL, addressing each
    instrument's ICL register."""
    runloop = next(s.count for s in steps if s.kind == "runloop")
    length = (
        f"the BIST needs up to {bist_cycles} {SYSTEM_CLOCK} cycles; the run loop adds a margin"
        if bist_cycles is not None
        else "the run loop is an upper bound on the BIST's length"
    )
    extest_bits = f"IR {ir_width}'b{format(extest, f'0{ir_width}b')}"
    if icl_file and bsdl_file:
        reach = [
            f"# ICL: {icl_file}",
            f"# BSDL: {bsdl_file}",
            "# The ICL's AccessLink names the TAP instruction that selects the IJTAG network",
            "# (declared in the BSDL); a retargeting tool loads it. Played without one, this PDL",
            f"# needs EXTEST ({extest_bits}) loaded first: the network sits behind that instruction.",
        ]
    else:
        reach = [
            f"# ICL: {icl_file}" if icl_file else "# ICL: rerun wrap-test-access with --emit-icl to write it.",
            "# The IJTAG network sits behind the TAP's data-register path: load EXTEST",
            f"# ({extest_bits}) before accessing it.",
        ]
    lines = [
        f"# IEEE 1687 PDL: run the memory BIST of {top} and check its result.",
        "# Generated by autombist wrap-test-access.",
        *reach,
        f"# iRunLoop counts the MBIST's functional clock, {SYSTEM_CLOCK}: {length}.",
        "",
        f"iProcsForModule {top}",
        "",
        "iProc run_mbist {} {",
    ]
    for step in steps:
        if step.kind == "write":
            lines.append(f"    iWrite {register_path[step.instrument]} {_binary(step.value, widths[step.instrument])}")
        elif step.kind == "read":
            lines.append(f"    iRead {register_path[step.instrument]} {_binary(step.value, widths[step.instrument])}")
        elif step.kind == "apply":
            lines.append("    iApply")
        elif step.kind == "runloop":
            lines.append(f"    iRunLoop {runloop} -sck {SYSTEM_CLOCK}")
        else:
            raise ValueError(f"unknown PDL step {step.kind!r}")
    lines += ["}", ""]
    return "\n".join(lines)


@dataclass(frozen=True)
class Vector:
    """One TCK cycle (``kind`` "tck": tms, tdi, the expected TDO and the read
    it's checked for, 0 = not checked) or ``count`` functional-clock cycles
    with TCK stopped in Run-Test/Idle (``kind`` "sck")."""

    kind: str
    tms: int = 0
    tdi: int = 0
    tdo: int = 0
    read: int = 0
    count: int = 0

    def line(self) -> str:
        if self.kind == "sck":
            return f"1 {self.count} 0 0 0"
        return f"0 {self.tms} {self.tdi} {self.tdo} {self.read}"


def retarget(graph: Any, root: Any, steps: list[PdlStep], *, ir_width: int, extest: int) -> list[Vector]:
    """Retarget ``steps`` to vectors through the inserted network (warptap's
    ``PDLInterpreter`` over ``graph``/``root``), starting and ending in
    Run-Test/Idle with EXTEST loaded first. Read ``k`` (1-based, in step order)
    marks the TDO bits it checks with ``read = k``."""
    from warptap.pdl_interpreter import PDLInterpreter
    from warptap.tap_fsm import TapState, next_state
    from warptap.tap_ir import GotoState, PulsePin, Runtest, ShiftDR, ShiftIR, bits_from_int
    from warptap.tap_ir_play import navigation_tms, shift_tms

    pdl = PDLInterpreter(graph, root)
    for step in steps:
        if step.kind == "write":
            pdl.iTarget(step.instrument)
            pdl.iWrite(step.value)
        elif step.kind == "read":
            pdl.iTarget(step.instrument)
            pdl.iRead(step.value)
        elif step.kind == "apply":
            pdl.iApply()
        elif step.kind == "runloop":
            pdl.iRunLoop(step.count, sck_port=SYSTEM_CLOCK)
    ops = [
        GotoState(TapState.SHIFT_IR),
        ShiftIR(ir_width, tdi=extest),
        GotoState(TapState.RUN_TEST_IDLE),
        *pdl.program,
    ]

    vectors: list[Vector] = []
    state = TapState.RUN_TEST_IDLE
    reads = 0
    for op in ops:
        if isinstance(op, GotoState):
            for tms in navigation_tms(state, op.state):
                vectors.append(Vector("tck", tms=tms))
                state = next_state(state, tms)
        elif isinstance(op, (ShiftIR, ShiftDR)):
            tdi = bits_from_int(op.tdi, op.bits)
            # An iRead fills in a ShiftDR's expected TDO and the mask of the
            # bits it checks: bit i of both belongs to the i-th shift cycle.
            expected = [0] * op.bits
            care = [0] * op.bits
            read = 0
            if isinstance(op, ShiftDR) and op.tdo is not None:
                reads += 1
                read = reads
                expected = bits_from_int(op.tdo, op.bits)
                care = bits_from_int((1 << op.bits) - 1 if op.mask is None else op.mask, op.bits)
            for i, tms in enumerate(shift_tms(op.bits)):
                vectors.append(Vector("tck", tms=tms, tdi=tdi[i], tdo=expected[i] if care[i] else 0,
                                      read=read if care[i] else 0))
                state = next_state(state, tms)
        elif isinstance(op, Runtest):
            vectors.extend(Vector("tck") for _ in range(op.count))
            for _ in range(op.count):
                state = next_state(state, 0)
        elif isinstance(op, PulsePin):
            vectors.append(Vector("sck", count=op.count))
        else:
            raise TestbenchError(f"can't retarget {op!r} to vectors")
    if reads != sum(1 for s in steps if s.kind == "read"):
        raise TestbenchError(
            f"retargeting produced {reads} checked shifts for "
            f"{sum(1 for s in steps if s.kind == 'read')} reads"
        )
    if state != TapState.RUN_TEST_IDLE:
        raise TestbenchError(f"retargeted vectors end in {state}, not Run-Test/Idle")
    return vectors


@dataclass(frozen=True)
class NetlistPort:
    name: str
    direction: str
    range: str  # "[3:0] " or ""


def parse_netlist_ports(verilog: str, module: str) -> list[NetlistPort]:
    """``module``'s ports in a Yosys-written (non-ANSI) netlist, in header order,
    with each one's direction and width from its declaration."""
    body = re.search(
        rf"^module\s+{re.escape(module)}\s*\((.*?)\);(.*?)^endmodule", verilog, re.DOTALL | re.MULTILINE
    )
    if body is None:
        raise TestbenchError(f"no module {module!r} in the wrapped netlist")
    order = [p.strip() for p in body.group(1).split(",") if p.strip()]
    decls = {
        name: (direction, f"{rng} " if rng else "")
        for direction, rng, name in re.findall(
            r"^\s*(input|output)\s+(?:wire\s+|reg\s+)?(\[[^\]]*\])?\s*([A-Za-z_]\w*)\s*;", body.group(2), re.MULTILINE
        )
    }
    missing = [p for p in order if p not in decls]
    if missing:
        raise TestbenchError(f"no direction declared for port(s) {missing} of {module!r}")
    return [NetlistPort(name, *decls[name]) for name in order]


def render_jtag_testbench(
    top: str,
    ports: list[NetlistPort],
    *,
    vectors_file: str,
    pdl_file: str,
    read_labels: list[str],
) -> str:
    names = {p.name for p in ports}
    missing = [p for p in (*_DRIVEN, "tdo") if p not in names]
    if missing:
        raise TestbenchError(f"wrapped {top!r} has no {', '.join(missing)} port")
    special = {*_DRIVEN, "tdo"}
    context = {
        "top": top,
        "ports": ports,
        "vectors_file": vectors_file,
        "pdl_file": pdl_file,
        "read_labels": read_labels,
        "idle_inputs": [
            {"name": p.name, "range": p.range, "idle": "'1" if p.name in _IDLE_HIGH else "'0"}
            for p in ports if p.direction == "input" and p.name not in special
        ],
        "outputs": [p for p in ports if p.direction == "output" and p.name != "tdo"],
    }
    return _render_template(context, "jtag_tb_template.sv.j2")


@dataclass(frozen=True)
class JtagBistFiles:
    pdl: Path
    vectors: Path
    testbench: Path
    run_script: Path


def write_jtag_bist(
    out: Path,
    *,
    top: str,
    graph: Any,
    root: Any,
    wrapped_verilog: str,
    wrapped_file: str,
    memory_name: str | None,
    run_cycles: int,
    bist_cycles: int | None,
    icl_file: str | None,
    bsdl_file: str | None = None,
) -> JtagBistFiles:
    """Write ``<top>_run_mbist.pdl``, ``<top>_run_mbist.vec``,
    ``tb_<top>_jtag.sv`` and ``run_tb_jtag.sh`` into ``out`` (the directory
    holding ``wrapped_file``)."""
    from warptap.icl_emit import INSTRUMENT_MODULE_PREFIX
    from warptap.tap_model import DEFAULT_IR_WIDTH, OPCODE_EXTEST

    steps = run_mbist_steps(run_cycles)
    widths = {node.instrument.name: node.instrument.width for node in graph.chain if node.instrument is not None}
    used = {s.instrument for s in steps if s.instrument is not None}
    absent = sorted(used - set(widths))
    if absent:
        raise TestbenchError(f"the IJTAG network wraps no {', '.join(absent)} port")
    register_path = {name: f"{INSTRUMENT_MODULE_PREFIX}{name}.DR" for name in used}

    out = Path(out)
    pdl = out / f"{top}_run_mbist.pdl"
    pdl.write_text(
        render_pdl(top, steps, widths=widths, register_path=register_path, icl_file=icl_file,
                   ir_width=DEFAULT_IR_WIDTH, extest=OPCODE_EXTEST, bist_cycles=bist_cycles,
                   bsdl_file=bsdl_file),
        encoding="utf-8",
    )
    vectors = retarget(graph, root, steps, ir_width=DEFAULT_IR_WIDTH, extest=OPCODE_EXTEST)
    vec = out / f"{top}_run_mbist.vec"
    vec.write_text("".join(v.line() + "\n" for v in vectors), encoding="utf-8")

    labels = [f"{s.instrument} = {s.value}" for s in steps if s.kind == "read"]
    tb_file = f"tb_{top}_jtag.sv"
    tb = out / tb_file
    tb.write_text(
        render_jtag_testbench(top, parse_netlist_ports(wrapped_verilog, top),
                              vectors_file=vec.name, pdl_file=pdl.name, read_labels=labels),
        encoding="utf-8",
    )
    # Wrapped from the memory's blackbox stub (wrap-test-access --manifest), the
    # netlist has no memory module and needs the model; wrapped from sources
    # that included the model, it already has it. With no config to name the
    # memory, the model is left optional.
    model_inside = memory_name is None or re.search(
        rf"^module\s+\\?{re.escape(memory_name)}\b", wrapped_verilog, re.MULTILINE
    ) is not None
    # `generate` writes a behavioral model of the memory into tb/ next to the output
    # directory this runs from (wrap-test-access --manifest); use it when no model is
    # given, so this script runs bare like tb/run_tb.sh does.
    default_model = None
    if not model_inside and memory_name is not None:
        generated = out.parent / TB_DIRNAME / f"{memory_name}_model.v"
        if generated.is_file():
            default_model = f"../{TB_DIRNAME}/{generated.name}"
    run_sh = out / "run_tb_jtag.sh"
    run_sh.write_text(
        render_run_script(
            what="JTAG MBIST testbench",
            top=top,
            memory_name=memory_name or "the memory",
            script=f"{out.name}/run_tb_jtag.sh",
            tb_module=f"tb_{top}_jtag",
            tb_file=tb_file,
            out_rel=".",
            sources=[wrapped_file],
            timeout_define=False,
            model_required=not model_inside,
            default_model=default_model,
            data_files=(vec.name,),
        ),
        encoding="utf-8",
    )
    _chmod_x(run_sh)
    return JtagBistFiles(pdl, vec, tb, run_sh)
