"""A behavioral simulation model of the memory a generated wrapper instantiates,
so the testbench `generate` writes (tb/) can run the BIST with no memory model
supplied.

The ports are the ones ``manifest.render_memory_stub`` declares for the same
config (the stub is the single source of truth for what the wrapper connects);
this adds behavior. It is idealized: no timing checks, contents power up unknown,
and it is fault-free. It is NOT the macro's own model -- the testbench's run
script replaces it with the macro's model when one is passed.

Read timing follows ``read_latency``: 0 is the style of a real OpenRAM macro
(inputs registered on the rising edge, the write and the read done on the
falling edge, so read data is valid before the next rising edge, where a
latency-0 controller samples it); 1 or more is the registered-read style of the
repo's other ``sram_*`` models (data one clock after the registered access,
held until the next read, which also satisfies any larger latency).
"""
from __future__ import annotations

from typing import Any

from .manifest import _geometry, _memory_connection_widths, _ports, _redundancy_flags


class MemoryModelError(ValueError):
    """The config describes a memory this model cannot be derived for."""

    __test__ = False


def render_memory_model(config: dict[str, Any]) -> str:
    """Verilog for a behavioral model named ``config['memory_name']`` with exactly
    the ports (names, directions, widths) of ``render_memory_stub(config)``."""
    geo = _geometry(config)
    flags = _redundancy_flags(config)
    addr_w, data_w = _memory_connection_widths(config, flags)
    logical_w = geo["data_width"]
    lanes = data_w - logical_w
    if lanes < 0:
        raise MemoryModelError(
            f"the memory is connected {data_w} data bits but the config's data_width is {logical_w}"
        )
    spare_w = max(1, geo["num_spare_cols"])
    latency = geo["read_latency"]
    we_active_low = bool(config.get("we_active_low", True))
    ports = list(_ports(config).values())

    # Declarations in the stub's order; a pin that serves the same role on several
    # ports (a shared clock) is declared once.
    decls: dict[str, str] = {}

    def add(name: str, decl: str) -> None:
        decls.setdefault(name, decl)

    for pdata in ports:
        ptype = pdata["type"]
        add(pdata["clk"], f"input  wire {pdata['clk']}")
        add(pdata["csb"], f"input  wire {pdata['csb']}")
        if ptype in ("w", "rw"):
            add(pdata["we"], f"input  wire {pdata['we']}")
        add(pdata["addr"], f"input  wire [{addr_w - 1}:0] {pdata['addr']}")
        if ptype in ("w", "rw"):
            add(pdata["din"], f"input  wire [{data_w - 1}:0] {pdata['din']}")
        if pdata.get("spare_wen"):
            add(pdata["spare_wen"], f"input  wire [{spare_w - 1}:0] {pdata['spare_wen']}")
        if ptype in ("r", "rw"):
            add(pdata["dout"], f"output reg  [{data_w - 1}:0] {pdata['dout']}")

    # A multi-port controller's algorithm expects a read concurrent with a same-address
    # write on another port to return the NEW data (march_1r1w_algo.sv, "write-forwarding").
    # The registered-read style gets that from write-then-read ordering; the falling-edge
    # style does both on one edge, so each reading port forwards the other ports' pending
    # writes explicitly, from the registered values (stable at the falling edge, so the
    # result does not depend on the order the ports' blocks run in).
    forward = latency == 0 and len(ports) > 1
    body: list[str] = []
    for i, pdata in enumerate(ports):
        body += _port_behavior(i, pdata, addr_w=addr_w, data_w=data_w, lanes=lanes,
                               latency=latency, we_active_low=we_active_low, forward=forward)
    if forward:
        for i, pdata in enumerate(ports):
            if pdata["type"] in ("r", "rw"):
                body += _forward_function(i, ports, addr_w=addr_w, data_w=data_w, lanes=lanes,
                                          we_active_low=we_active_low)

    style = (
        "inputs registered on the rising clock edge, the write and the read done on the "
        "falling edge, a read forwarding a same-edge write from another port (read_latency 0)"
        if latency == 0 and forward
        else "inputs registered on the rising clock edge, the write and the read done on the "
        "falling edge (read_latency 0)"
        if latency == 0
        else "writes on the rising edge, reads one clock after the registered access, data held "
        f"until the next read (read_latency {latency})"
    )
    lines = [
        "`timescale 1ns/1ps",
        "// Auto-generated by autombist from config.yml: a BEHAVIORAL model of the memory,",
        f"// {style}.",
        "// Idealized: fault-free, no timing checks, contents power up unknown. It is NOT the",
        "// macro's own model; pass that model to run_tb.sh to replace this one.",
        f"module {config['memory_name']} #(",
        f"    parameter integer ADDR_WIDTH = {geo['addr_width']},",
        f"    parameter integer DATA_WIDTH = {geo['data_width']},",
        f"    parameter integer NUM_SPARE_ROWS = {geo['num_spare_rows']},",
        f"    parameter integer NUM_SPARE_COLS = {geo['num_spare_cols']}",
        ") (",
        ",\n".join(f"    {d}" for d in decls.values()),
        ");",
        "    // The wrapper overrides the parameters above; the widths below are the ones it connects.",
        f"    localparam integer LOGICAL_W = {logical_w};",
        f"    localparam integer DEPTH = {1 << addr_w};",
        f"    reg [{data_w - 1}:0] mem [0:DEPTH-1];",
        "",
        *body,
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def _terms(has_we: bool, we: str | None, we_active_low: bool) -> tuple[str, str]:
    """(write, read) conditions on a ``we`` value: a write-only port always writes
    and a read-only port always reads."""
    if not has_we:
        return "1'b0", "1'b1"
    return (f"!{we}", we) if we_active_low else (we, f"!{we}")


def _store(addr: str, din: str, spare_wen: str | None, lanes: int, k: str) -> list[str]:
    """Statements writing ``din`` to ``mem[addr]``: the logical bits always, and a
    spare lane only under its ``spare_wen`` bit (a spare lane is never written as a
    side effect of a word store)."""
    if lanes == 0 or spare_wen is None:
        return [f"mem[{addr}] <= {din};"]
    return [
        f"mem[{addr}][LOGICAL_W-1:0] <= {din}[LOGICAL_W-1:0];",
        f"for ({k} = 0; {k} < {lanes}; {k} = {k} + 1)",
        f"    if ({spare_wen}[{k}]) mem[{addr}][LOGICAL_W + {k}] <= {din}[LOGICAL_W + {k}];",
    ]


def _forward_function(
    r: int, ports: list[dict[str, Any]], *, addr_w: int, data_w: int, lanes: int, we_active_low: bool
) -> list[str]:
    """``p<r>_read(a)``: the stored word at ``a`` with the write each OTHER port makes on
    this same falling edge applied (a spare lane only where its ``spare_wen`` bit is set)."""
    p = f"p{r}"
    out = [
        f"    // port {r}'s read: the stored word, with the write another port makes on this edge",
        f"    function [{data_w - 1}:0] {p}_read(input [{addr_w - 1}:0] a);",
        f"        reg [{data_w - 1}:0] v;",
        "        integer k;",
        "        begin",
        "            v = mem[a];",
    ]
    for w, wdata in enumerate(ports):
        if w == r or wdata["type"] not in ("w", "rw"):
            continue
        q = f"p{w}"
        write_q, _ = _terms(True, f"{q}_we_q", we_active_low)
        spare = wdata.get("spare_wen") if lanes else None
        out.append(f"            if (!{q}_csb_q && {write_q} && {q}_addr_q == a) begin")
        if spare is None:
            out.append(f"                v = {q}_din_q;")
        else:
            out += [
                f"                v[LOGICAL_W-1:0] = {q}_din_q[LOGICAL_W-1:0];",
                f"                for (k = 0; k < {lanes}; k = k + 1)",
                f"                    if ({q}_spare_q[k]) v[LOGICAL_W + k] = {q}_din_q[LOGICAL_W + k];",
            ]
        out.append("            end")
    out += [f"            {p}_read = v;", "        end", "    endfunction", ""]
    return out


def _port_behavior(
    i: int, pdata: dict[str, Any], *, addr_w: int, data_w: int, lanes: int, latency: int,
    we_active_low: bool, forward: bool = False,
) -> list[str]:
    p = f"p{i}"
    ptype = pdata["type"]
    has_we = ptype in ("w", "rw")
    does_read = ptype in ("r", "rw")
    clk, csb, addr = pdata["clk"], pdata["csb"], pdata["addr"]
    we, din, dout = pdata.get("we"), pdata.get("din"), pdata.get("dout")
    spare_wen = pdata.get("spare_wen") if lanes else None
    k = f"{p}_k"
    write_live, _ = _terms(has_we, we, we_active_low)
    write_q, read_q = _terms(has_we, f"{p}_we_q" if has_we else None, we_active_low)

    out = [f"    // port {i}: {ptype}", f"    reg {p}_csb_q;", f"    reg [{addr_w - 1}:0] {p}_addr_q;"]
    if has_we:
        out.append(f"    reg {p}_we_q;")
        if latency == 0:
            out.append(f"    reg [{data_w - 1}:0] {p}_din_q;")
            if spare_wen:
                out.append(f"    reg [{lanes - 1}:0] {p}_spare_q;")
        if spare_wen:
            out.append(f"    integer {k};")

    out.append(f"    always @(posedge {clk}) begin")
    out += [f"        {p}_csb_q  <= {csb};", f"        {p}_addr_q <= {addr};"]
    if has_we:
        out.append(f"        {p}_we_q   <= {we};")
    if latency == 0:
        if has_we:
            out.append(f"        {p}_din_q  <= {din};")
            if spare_wen:
                out.append(f"        {p}_spare_q <= {spare_wen}[{lanes - 1}:0];")
        out.append("    end")
        out.append(f"    always @(negedge {clk}) begin")
        if has_we:
            out.append(f"        if (!{p}_csb_q && {write_q}) begin")
            out += [f"            {s}" for s in _store(f"{p}_addr_q", f"{p}_din_q",
                                                        f"{p}_spare_q" if spare_wen else None, lanes, k)]
            out.append("        end")
    elif has_we:
        out.append(f"        if (!{csb} && {write_live}) begin")
        out += [f"            {s}" for s in _store(addr, din, spare_wen, lanes, k)]
        out.append("        end")
    if does_read:
        word = f"{p}_read({p}_addr_q)" if forward else f"mem[{p}_addr_q]"
        out.append(f"        if (!{p}_csb_q && {read_q}) {dout} <= {word};")
    out += ["    end", ""]
    return out
